// Auto-generated by build-prompts.js. DO NOT EDIT.
import { instructionPrompt } from './instruction.js';
import { node1Prompt } from './node1.js';
import { node2Prompt } from './node2.js';
import { node3Prompt } from './node3.js';
import { node4Prompt } from './node4.js';
import { node5Prompt } from './node5.js';
import { node6aPrompt } from './node6a.js';
import { node6bPrompt } from './node6b.js';
import { node7Prompt } from './node7.js';
import { node8Prompt } from './node8.js';

export const prompts = {
  instruction: instructionPrompt,
  node1: node1Prompt,
  node2: node2Prompt,
  node3: node3Prompt,
  node4: node4Prompt,
  node5: node5Prompt,
  node6a: node6aPrompt,
  node6b: node6bPrompt,
  node7: node7Prompt,
  node8: node8Prompt
};
