import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_DIR = join(__dirname, 'legacy', 'CRSM');
const OUT_DIR = join(__dirname, 'src', 'crsm', 'prompts');

const FILES = [
  ['Instruction.md', 'instruction'],
  ['NODE_1.md', 'node1'],
  ['NODE_2.md', 'node2'],
  ['NODE_3.md', 'node3'],
  ['NODE_4.md', 'node4'],
  ['NODE_5.md', 'node5'],
  ['NODE_6A.md', 'node6a'],
  ['NODE_6B.md', 'node6b'],
  ['NODE_7_LOG.md', 'node7'],
  ['NODE_8.md', 'node8']
];

function escapeTemplateLiteral(text) {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

mkdirSync(OUT_DIR, { recursive: true });

for (const [fileName, exportName] of FILES) {
  const markdown = readFileSync(join(SOURCE_DIR, fileName), 'utf8').trim();
  const moduleContent = `// Auto-generated from legacy/CRSM/${fileName} by build-prompts.js. DO NOT EDIT.\nexport const ${exportName}Prompt = \`${escapeTemplateLiteral(markdown)}\`;\n`;
  writeFileSync(join(OUT_DIR, `${exportName}.js`), moduleContent, 'utf8');
  console.log(`generated src/crsm/prompts/${exportName}.js`);
}

writeFileSync(
  join(OUT_DIR, 'index.js'),
  `// Auto-generated by build-prompts.js. DO NOT EDIT.\nimport { instructionPrompt } from './instruction.js';\nimport { node1Prompt } from './node1.js';\nimport { node2Prompt } from './node2.js';\nimport { node3Prompt } from './node3.js';\nimport { node4Prompt } from './node4.js';\nimport { node5Prompt } from './node5.js';\nimport { node6aPrompt } from './node6a.js';\nimport { node6bPrompt } from './node6b.js';\nimport { node7Prompt } from './node7.js';\nimport { node8Prompt } from './node8.js';\n\nexport const prompts = {\n  instruction: instructionPrompt,\n  node1: node1Prompt,\n  node2: node2Prompt,\n  node3: node3Prompt,\n  node4: node4Prompt,\n  node5: node5Prompt,\n  node6a: node6aPrompt,\n  node6b: node6bPrompt,\n  node7: node7Prompt,\n  node8: node8Prompt\n};\n`,
  'utf8'
);
console.log('generated src/crsm/prompts/index.js');