import { parseTradingViewPaste } from './parser.js';
import { buildPrompt, buildStats, scoreStocks } from './scoring.js';
import { crsmState, subscribeCRSM } from './crsm/state.js';
import { buildScreeningContext } from './crsm/context.js';
import { runCRSM } from './crsm/engine.js';
import { renderCRSMTab, bindCRSMUIBindings, updateDynamicRegion } from './crsm/ui/index.js';
import { renderSettings, bindSettingsEvents } from './crsm/ui/settings.js';
import { loadLog } from './crsm/nodes/node7.js';
import { downloadReportImage, downloadWordReport } from './crsm/report-export.js';

const STORAGE_KEY = 'stock-mind.dataset.v1';
let state = { tab:'import', crsmView:'analysis', reportTab:'html', pasteText:'', rows:loadRows(), errors:[], selectedTicker:null, selectedTickers:[], search:'', batchRunning:false, batchProgress:null, importStatus:null, settingsOpen:false };
const app=document.getElementById('app');
subscribeCRSM(()=>{
  if (crsmState.completedAt && crsmState.finalReport && !crsmState.isRunning && !crsmState.failedNode && !crsmState.error) {
    if (state.tab === 'crsm') { state.crsmView='reports'; render(); return; }
  }
  if(state.tab==='crsm' && state.crsmView==='analysis') updateDynamicRegion();
  if(state.tab==='crsm' && state.crsmView==='reports') updateReportsRegion();
});
render();

function render(){ app.innerHTML=`<div class="shell">${renderTopbar()}<main class="main">${state.tab==='import'?renderImport():''}${state.tab==='dashboard'?renderDashboard():''}${state.tab==='list'?renderList():''}${state.tab==='detail'?renderDetail():''}${state.tab==='crsm'?renderCRSMSection():''}${state.settingsOpen?renderSettings():''}</main></div>`; bindEvents(); if(state.settingsOpen) bindSettingsEvents(); }
function renderTopbar(){ const tabs=[['import','Screen'],['dashboard','Dashboard'],['list','Ranking'],['crsm','CRSM']]; return `<header class="topbar"><div class="topbar-inner"><div class="brand"><div class="brand-mark">↗</div><span>Stock Mind</span></div><nav class="tabs">${tabs.map(([id,label])=>`<button class="tab ${state.tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}<button class="tab ${state.settingsOpen?'active':''}" id="openSettings" type="button">⚙ Settings</button></nav></div></header>`; }
function renderCRSMSection(){ const active=state.crsmView==='reports'?'reports':'analysis'; return `<section class="crsm-shell"><div class="crsm-subnav" role="tablist"><button class="crsm-subtab ${active==='analysis'?'active':''}" data-crsm-view="analysis">Analysis</button><button class="crsm-subtab ${active==='reports'?'active':''}" data-crsm-view="reports">Reports${loadLog().rows.length?` <span class="report-count">${loadLog().rows.length}</span>`:''}</button></div>${active==='reports'?renderReports():renderCRSMTab()}</section>`; }
function renderImport(){ const status=state.importStatus||(state.rows.length?{count:state.rows.length,columns:null,time:null}:null); return `<section class="screen-page"><div class="screen-hero"><div class="screen-copy"><p class="eyebrow">Stock Screening</p><h1>From TradingView<br>to Stock Mind</h1><p class="screen-lead">Lọc cổ phiếu trên TradingView, copy toàn bộ bảng kết quả, rồi đưa thẳng vào Stock Mind.</p><div class="screen-actions"><button class="btn primary screen-action" id="openTradingView">Open TradingView <span>↗</span></button><button class="btn screen-action" id="importClipboard">Import &amp; Screen</button></div><p class="screen-hint">TradingView → Ctrl+A → Ctrl+C → Import &amp; Screen</p>${status?`<div class="screen-status"><strong>${status.count.toLocaleString('vi-VN')} mã</strong><span>${status.columns?`${status.columns} cột`:'Screening data'}${status.time?` · ${escapeHtml(status.time)}`:''}</span></div>`:''}${state.errors.length?`<div class="errors" style="margin-top:14px">${state.errors.map(escapeHtml).join('<br>')}</div>`:''}</div><div class="screen-visual" aria-hidden="true"><div class="screen-orbit orbit-one"></div><div class="screen-orbit orbit-two"></div><div class="screen-flow-card flow-tv"><div class="flow-card-top"><span class="flow-dot"></span><span>TRADINGVIEW</span></div><div class="mini-table"><i></i><i></i><i></i><i></i><i></i></div><div class="mini-bars"><b></b><b></b><b></b><b></b></div></div><div class="screen-flow-arrow">→</div><div class="screen-flow-card flow-rank"><div class="flow-card-top"><span class="flow-dot"></span><span>STOCK MIND</span></div><div class="rank-row"><strong>#01</strong><span>VCB</span><em>A+</em></div><div class="rank-row"><strong>#02</strong><span>HPG</span><em>A</em></div><div class="rank-row"><strong>#03</strong><span>HAH</span><em>A</em></div></div><div class="screen-flow-card flow-crsm"><div class="flow-card-top"><span class="flow-dot"></span><span>CRSM</span></div><div class="crsm-pulse"></div><small>Deep analysis</small></div><div class="screen-caption"><span>01</span> Copy your screen <span>02</span> Rank candidates <span>03</span> Analyze deeply</div></div></div></section>`; }
function renderDashboard(){ if(!state.rows.length)return emptyState(); const stats=buildStats(state.rows),industries=Object.entries(stats.industryCount).sort((a,b)=>b[1]-a[1]).slice(0,8); return `<section class="grid"><div class="grid metrics">${metric('Tổng mã',stats.total)}${metric('Điểm TB',fmt(stats.avgScore))}${metric('Ngành',Object.keys(stats.industryCount).length)}${metric('Top Grade',stats.top10[0]?.GRADE||'-')}</div><div class="grid two"><div class="panel panel-pad"><div class="title-row"><div><p class="eyebrow">Top 10</p><h2>Sức mạnh tổng hợp</h2></div></div>${stats.top10.map(row=>stockLine(row)).join('')}</div><div class="panel panel-pad"><div class="title-row"><div><p class="eyebrow">Industries</p><h2>Phân bổ ngành</h2></div></div>${industries.map(([name,count])=>`<div class="stock-line"><span>${escapeHtml(name)}</span><strong>${count} mã</strong></div>`).join('')}</div></div></section>`; }
function renderList(){ if(!state.rows.length)return emptyState(); const rows=state.rows.filter(row=>{const q=state.search.trim().toLowerCase(); return !q||String(row.TICKER||'').toLowerCase().includes(q)||String(row.INDUSTRY||'').toLowerCase().includes(q)}); const visibleTickers=rows.map(r=>r.TICKER),selectedVisible=visibleTickers.filter(t=>state.selectedTickers.includes(t)),allVisibleSelected=visibleTickers.length>0&&selectedVisible.length===visibleTickers.length; return `<section class="panel panel-pad"><div class="toolbar"><div><p class="eyebrow">Ranking</p><h2>${rows.length} mã</h2><p class="muted">Bấm trực tiếp vào <strong>ticker</strong> để chạy một mã. Hoặc chọn nhiều mã rồi bấm <strong>Run CRSM</strong>.</p></div><input class="search" id="searchInput" value="${escapeHtml(state.search)}" placeholder="Tìm ticker hoặc ngành" autocomplete="off"></div><div class="actions" style="margin-bottom:14px"><button class="btn" id="selectVisibleCRSM">${allVisibleSelected?'Bỏ chọn tất cả':'Chọn tất cả'}</button><button class="btn primary" id="runSelectedCRSM" ${state.selectedTickers.length||state.batchRunning?'':'disabled'}>Run CRSM${state.selectedTickers.length?` (${state.selectedTickers.length})`:''}</button>${state.selectedTickers.length?'<button class="btn" id="clearSelectedCRSM">Bỏ chọn</button>':''}</div><div class="table-wrap"><table><thead><tr><th><input type="checkbox" id="selectAllCRSM" ${allVisibleSelected?'checked':''}></th><th>Rank</th><th>Ticker</th><th>Industry</th><th>Price</th><th>P/E</th><th>Quality</th><th>Growth</th><th>Value</th><th>Micro</th><th>Momentum</th><th>Opportunity</th><th>Final</th><th>Grade</th></tr></thead><tbody>${rows.map(row=>`<tr><td><input type="checkbox" class="crsm-select" data-select-ticker="${row.TICKER}" ${state.selectedTickers.includes(row.TICKER)?'checked':''}></td><td>#${row.RANK}</td><td class="ticker"><button class="crsm-link ticker-run" data-crsm="${row.TICKER}" title="Chạy CRSM cho ${row.TICKER}">${row.TICKER}</button><span class="data-flags">${renderFlags(row)}</span></td><td>${escapeHtml(row.INDUSTRY)}</td><td>${fmt(row.PRICE)}</td><td>${fmt(row.PE)}</td><td>${fmt(row.QUALITY_SCORE)}</td><td>${fmt(row.GROWTH_SCORE)}</td><td>${fmt(row.VALUATION_SCORE)}</td><td>${fmt(row.MICRO)}</td><td>${fmt(row.MOMENTUM)}</td><td>${fmt(row.MISPRICING)}</td><td><strong>${fmt(row.FINALSCORE)}</strong></td><td>${gradeBadge(row.GRADE)}</td></tr>`).join('')}</tbody></table></div></section>`; }
function renderDetail(){ const stock=state.rows.find(r=>r.TICKER===state.selectedTicker)||state.rows[0]; if(!stock)return emptyState(); const prompt=buildPrompt(stock); return `<section class="grid"><div class="detail-head"><div class="panel panel-pad"><p class="eyebrow">${escapeHtml(stock.INDUSTRY)}</p><h1>${stock.TICKER}</h1><div class="score-big">${fmt(stock.FINALSCORE)}</div><p>Rank #${stock.RANK} · ${gradeBadge(stock.GRADE)}</p><button class="btn primary" data-crsm="${stock.TICKER}">Phân tích bằng CRSM →</button></div><div class="panel panel-pad"><p class="eyebrow">Score Breakdown</p><div class="score-grid">${scoreCard('Quality',stock.QUALITY_SCORE)}${scoreCard('Growth',stock.GROWTH_SCORE)}${scoreCard('Valuation',stock.VALUATION_SCORE)}${scoreCard('Micro',stock.MICRO)}${scoreCard('Momentum',stock.MOMENTUM)}${scoreCard('Opportunity',stock.MISPRICING)}</div></div></div><div class="panel panel-pad"><div class="title-row"><div><p class="eyebrow">AI Prompt</p><h2>Prompt phân tích tối ưu</h2></div><button class="btn primary" id="copyPrompt">Copy prompt</button></div><textarea class="prompt" id="promptText" readonly>${escapeHtml(prompt)}</textarea></div></section>`; }
function renderReports(){ const report=crsmState.finalReport||crsmState.nodeOutputs.node6a; const log=loadLog().rows||[]; if(!report&&!log.length)return emptyState(); return `<section class="reports-page"><div class="reports-head"><div><p class="eyebrow">CRSM REPORT</p><h1>Báo cáo &amp; lịch sử · ${escapeHtml(crsmState.ticker||'')}</h1><p class="muted">Visual report, detailed export và decision log của CRSM.</p></div>${report?`<div class="actions"><button class="btn primary" id="crsmDownloadImage">Tải ảnh</button><button class="btn" id="crsmDownloadWord">Tải Word</button></div>`:''}</div><div class="report-tabs"><button class="report-tab ${state.reportTab==='html'?'active':''}" data-report-tab="html">HTML</button><button class="report-tab ${state.reportTab==='word'?'active':''}" data-report-tab="word">Word</button><button class="report-tab ${state.reportTab==='log'?'active':''}" data-report-tab="log">Decision Log${log.length?` <span class="report-count">${log.length}</span>`:''}</button></div>${state.reportTab==='log'?renderDecisionLog(log):`<div class="report-paper"><iframe class="crsm-report-frame" srcdoc="${escapeAttr(report||'<div style=\"padding:24px;font-family:sans-serif\">Chưa có Visual Report.</div>')}" sandbox></iframe></div>`}</section>`; }
function renderDecisionLog(rows){ const columns=[['date','Ngày phân tích'],['ticker','Mã'],['mode','Chế độ'],['price_at_analysis','Giá tại thời điểm PT'],['screen_score','Screen Score'],['screen_rank','Screen Rank'],['screen_grade','Screen Grade'],['decision','Quyết định'],['ai_score','AI Score'],['confidence','Confidence'],['score_difference','CRSM−Screen Diff'],['entry_zone','Entry'],['trading_stop','Trading Stop'],['tp1','TP1'],['tp2','TP2'],['thesis_invalidation','Thesis Invalidation']]; return `<div class="panel panel-pad decision-log-panel"><div class="title-row"><div><p class="eyebrow">DECISION LOG</p><h2>${rows.length} lần phân tích</h2><p class="muted">Append-only history · DIRECT dùng — cho các trường không áp dụng.</p></div></div>${rows.length?`<div class="table-wrap decision-log-wrap"><table class="decision-log-table"><thead><tr>${columns.map(([,label])=>`<th>${label}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(([key])=>`<td>${formatLogValue(row[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">Chưa có decision log.</div>'}</div>`; }
function formatLogValue(value){ if(value==null||value==='')return '—'; if(typeof value==='number')return Number.isFinite(value)?value.toLocaleString('vi-VN',{maximumFractionDigits:2}):'—'; return escapeHtml(String(value)); }
function updateReportsRegion(){ if(state.tab==='crsm'&&state.crsmView==='reports') render(); }
function bindEvents(){ document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;if(state.tab==='crsm')state.crsmView='analysis';render();})); document.querySelectorAll('[data-crsm-view]').forEach(b=>b.addEventListener('click',()=>{state.crsmView=b.dataset.crsmView;render();})); document.querySelectorAll('[data-report-tab]').forEach(b=>b.addEventListener('click',()=>{state.reportTab=b.dataset.reportTab;render();})); document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();state.selectedTicker=b.dataset.detail;state.tab='detail';render();})); document.querySelectorAll('[data-crsm]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();launchScreenedCRSM(b.dataset.crsm);})); document.querySelectorAll('[data-select-ticker]').forEach(i=>i.addEventListener('change',e=>toggleSelectedTicker(e.target.dataset.selectTicker,e.target.checked))); bind('openTradingView','click',()=>window.open('https://www.tradingview.com/screener/','_blank','noopener,noreferrer')); bind('importClipboard','click',importFromClipboard); bind('copyPrompt','click',copyPrompt); bind('crsmRunDirect','click',runDirectCRSM); bind('openSettings','click',()=>{state.settingsOpen=!state.settingsOpen;render();}); bind('selectAllCRSM','change',e=>selectVisible(e.target.checked)); bind('selectVisibleCRSM','click',selectAllVisibleToggle); bind('clearSelectedCRSM','click',()=>{state.selectedTickers=[];render();}); bind('runSelectedCRSM','click',runSelectedCRSM); bind('crsmDownloadImage','click',async()=>downloadReportImage(crsmState.finalReport||crsmState.nodeOutputs.node6a,crsmState.ticker)); bind('crsmDownloadWord','click',()=>downloadWordReport(crsmState.finalReport||crsmState.nodeOutputs.node6a,crsmState.ticker)); bindCRSMUIBindings(); const crsmTickerInput=document.getElementById('crsmTickerInput'); if(crsmTickerInput)crsmTickerInput.addEventListener('keydown',e=>{if(e.key==='Enter')runDirectCRSM();}); const searchInput=document.getElementById('searchInput'); if(searchInput)searchInput.addEventListener('input',e=>{const value=e.target.value,s=e.target.selectionStart??value.length;state.search=value;render();const next=document.getElementById('searchInput');if(next){next.focus();try{next.setSelectionRange(s,s)}catch{}}}); }
function bind(id,event,handler){const n=document.getElementById(id);if(n)n.addEventListener(event,handler)}
async function importFromClipboard(){state.errors=[];try{if(!navigator.clipboard?.readText)throw new Error('Trình duyệt không hỗ trợ đọc Clipboard.');const text=await navigator.clipboard.readText();if(!text.trim())throw new Error('Clipboard đang trống.');const result=parseTradingViewPaste(text);state.errors=result.errors;if(result.errors.length||!result.rows.length){state.importStatus=null;render();return;}state.pasteText=text;state.rows=scoreStocks(result.rows);state.selectedTicker=state.rows[0]?.TICKER||null;state.selectedTickers=[];state.importStatus={count:state.rows.length,columns:result.rows[0]?Object.keys(result.rows[0]).length:null,time:new Date().toLocaleString('vi-VN')};localStorage.setItem(STORAGE_KEY,JSON.stringify(state.rows));state.tab='dashboard';render()}catch(error){state.errors=[error?.message||'Không thể đọc dữ liệu từ Clipboard.'];render()}}
function launchScreenedCRSM(ticker){const stock=state.rows.find(r=>r.TICKER===ticker);if(!stock)return;state.selectedTicker=ticker;state.tab='crsm';state.crsmView='analysis';render();runCRSM({mode:'SCREENED',ticker,screeningContext:buildScreeningContext(stock)})}
async function runSelectedCRSM(){if(state.batchRunning||!state.selectedTickers.length)return;const queue=[...state.selectedTickers];state.batchRunning=true;state.batchProgress={index:0,total:queue.length,ticker:queue[0]};state.tab='crsm';state.crsmView='analysis';render();for(let i=0;i<queue.length;i+=1){const ticker=queue[i],stock=state.rows.find(r=>r.TICKER===ticker);if(!stock)continue;state.batchProgress={index:i+1,total:queue.length,ticker};const result=await runCRSM({mode:'SCREENED',ticker,screeningContext:buildScreeningContext(stock)});if(result?.error)console.warn(`CRSM batch failed for ${ticker}`,result.error);await new Promise(r=>setTimeout(r,250));}state.batchRunning=false;state.batchProgress=null;state.selectedTickers=[];state.tab='crsm';state.crsmView='reports';render()}
async function runDirectCRSM(){const input=document.getElementById('crsmTickerInput'),ticker=(input?.value||'').trim().toUpperCase();if(!ticker)return;state.selectedTicker=ticker;setCrsmRunning();await runCRSM({mode:'DIRECT',ticker,screeningContext:null})}
function setCrsmRunning(){if(state.tab!=='crsm'){state.tab='crsm';state.crsmView='analysis';render()}else if(state.crsmView!=='analysis'){state.crsmView='analysis';render()}else updateDynamicRegion()}
function retryFailedCRSM(){const mode=crsmState.mode,ticker=crsmState.ticker,startFrom=crsmState.failedNode;if(mode&&ticker&&startFrom)runCRSM({mode,ticker,screeningContext:mode==='SCREENED'?crsmState.screeningContext:null,startFrom,existingOutputs:crsmState.nodeOutputs})}
function retryAllCRSM(){const mode=crsmState.mode,ticker=crsmState.ticker;if(mode&&ticker)runCRSM({mode,ticker,screeningContext:mode==='SCREENED'?crsmState.screeningContext:null,startFrom:'node1',existingOutputs:null,bypassCache:true})}
function toggleSelectedTicker(ticker,checked){const next=new Set(state.selectedTickers);if(checked)next.add(ticker);else next.delete(ticker);state.selectedTickers=[...next];render()}
function selectVisible(checked){const q=state.search.toLowerCase(),visible=state.rows.filter(r=>r.TICKER.toLowerCase().includes(q)||r.INDUSTRY.toLowerCase().includes(q)).map(r=>r.TICKER),next=new Set(state.selectedTickers);visible.forEach(t=>checked?next.add(t):next.delete(t));state.selectedTickers=[...next];render()}
function selectAllVisibleToggle(){const q=state.search.toLowerCase(),visible=state.rows.filter(r=>r.TICKER.toLowerCase().includes(q)||r.INDUSTRY.toLowerCase().includes(q)).map(r=>r.TICKER),all=visible.length>0&&visible.every(t=>state.selectedTickers.includes(t));selectVisible(!all)}
function copyPrompt(){const text=document.getElementById('promptText')?.value;if(text)navigator.clipboard?.writeText(text)}
function renderFlags(row){const flags=row.DATA_FLAGS||[];return flags.length?`<span title="${escapeHtml(flags.join(', '))}">⚠ ${flags.length}</span>`:''}
function loadRows(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):[]}catch{return[]}}
function emptyState(){return `<section class="panel panel-pad"><p class="eyebrow">No Data</p><h1>Chưa có dữ liệu cổ phiếu</h1><p class="muted">Hãy import bảng TradingView ở tab Screen để bắt đầu.</p><button class="btn primary" data-tab="import">Đi tới Screen</button></section>`}
function metric(label,value){return `<div class="panel metric"><p class="metric-label">${label}</p><p class="metric-value">${value}</p></div>`}
function stockLine(row){return `<div class="stock-line clickable" data-crsm="${row.TICKER}" title="Chạy CRSM cho ${row.TICKER}"><span><strong>${row.TICKER}</strong> <span class="muted">${escapeHtml(row.INDUSTRY)}</span></span><span>${fmt(row.FINALSCORE)} ${gradeBadge(row.GRADE)}</span></div>`}
function scoreCard(label,value){return `<div class="score-card"><span class="muted">${label}</span><strong>${fmt(value)}</strong></div>`}
function gradeBadge(grade){const cls=grade?.startsWith('A')?'grade-a':grade==='B'?'grade-b':grade==='C'?'grade-c':'grade-d';return `<span class="badge ${cls}">${grade||'-'}</span>`}
function fmt(value){if(value==null||Number.isNaN(value))return '-';if(typeof value==='number')return value.toLocaleString('vi-VN',{maximumFractionDigits:2});return value}
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}
function escapeAttr(value){return escapeHtml(value).replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}
