import { parseTradingViewPaste } from './parser.js';

const STORAGE_KEY = 'stock-mind.dataset.v1';
const TAB_ID = 'mapping-preview';
const TAB_LABEL = 'Mapping';
const COLUMNS = [
  ['ticker','Symbol','Ticker'],['company_name','Company','Company'],['sector','Sector','Sector'],['industry','Industry','Industry'],['market_cap','Market Cap','Market Cap'],['price','Price','Price'],['change_pct','Chg %','Change %'],['perf_1w','Perf 1W','1W'],['perf_1m','Perf 1M','1M'],['perf_3m','Perf 3M','3M'],['perf_6m','Perf 6M','6M'],['perf_1y','Perf 1Y','1Y'],['perf_ytd','Perf YTD','YTD'],['high_52w','High 52W','52W High'],['low_52w','Low 52W','52W Low'],['volume','Vol','Volume'],['relative_volume','Rel Vol','Relative Vol'],['avg_volume_10d','Avg Vol 10D','Avg Vol 10D'],['avg_volume_30d','Avg Vol 30D','Avg Vol 30D'],['avg_volume_60d','Avg Vol 60D','Avg Vol 60D'],['roe_ttm','ROE TTM','ROE TTM'],['roa_ttm','ROA TTM','ROA TTM'],['revenue_fq','Revenue FQ','Revenue FQ'],['revenue_fy','Revenue FY','Revenue FY'],['revenue_ttm','Revenue TTM','Revenue TTM'],['revenue_growth_quarterly_yoy','Revenue Growth Quarterly YoY','Revenue Growth Q YoY'],['revenue_growth_annual_yoy','Revenue Growth Annual YoY','Revenue Growth FY YoY'],['eps_dil_ttm','EPS Dil TTM','EPS TTM'],['eps_dil_growth_ttm_yoy','EPS Dil Growth TTM YoY','EPS Growth TTM YoY'],['peg_ttm','PEG TTM','PEG TTM'],['gross_margin_ttm','Gross Margin % TTM','Gross Margin TTM'],['operating_margin_ttm','Op Margin % TTM','Operating Margin TTM'],['net_margin_ttm','Net Margin % TTM','Net Margin TTM'],['fcf_ttm','FCF TTM','FCF TTM'],['fcf_growth_ttm_yoy','FCF Growth TTM YoY','FCF Growth TTM YoY'],['debt_equity_fq','Debt/Equity FQ','D/E FQ'],['debt_equity_fy','Debt/Equity FY','D/E FY'],['current_ratio_fq','Current Ratio FQ','Current Ratio FQ'],['current_ratio_fy','Current Ratio FY','Current Ratio FY'],['quick_ratio_fq','Quick Ratio FQ','Quick Ratio FQ'],['quick_ratio_fy','Quick Ratio FY','Quick Ratio FY'],['pe','P/E','P/E'],['peg','PEG','PEG'],['pb','P/B','P/B'],['ps','P/S','P/S'],['ev_ebitda','EV/EBITDA','EV/EBITDA'],['ev_revenue','EV/Revenue','EV/Revenue'],['dividend_yield_ttm','Div Yield % TTM','Dividend Yield TTM']
];
const DEBUG_COLUMNS=['symbol','ui_marker','sector','industry','market_cap','price','change_pct','perf_1w','perf_1m','perf_3m','perf_6m','perf_1y','perf_ytd','high_52w','low_52w','volume','relative_volume','avg_volume_10d','avg_volume_30d','avg_volume_60d','roe_ttm','roa_ttm','revenue_fq','revenue_fy','revenue_ttm','revenue_growth_quarterly_yoy','revenue_growth_annual_yoy','eps_dil_ttm','eps_dil_growth_ttm_yoy','peg_ttm','gross_margin_ttm','operating_margin_ttm','net_margin_ttm','fcf_ttm','fcf_growth_ttm_yoy','debt_equity_fq','debt_equity_fy','current_ratio_fq','current_ratio_fy','quick_ratio_fq','quick_ratio_fy','pe','peg','pb','ps','ev_ebitda','ev_revenue','dividend_yield_ttm'];
let previewOpen=false; let observerStarted=false;
let debugState={status:'Chưa lấy clipboard debug.',rawRow:[],parsedRow:null,result:null,error:null,rawText:'',lines:[],delimiter:'—',format:'—',tabCount:0,pipeCount:0};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function readRows(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return[];const d=JSON.parse(raw);return Array.isArray(d)?d:(Array.isArray(d.rows)?d.rows:Array.isArray(d.data)?d.data:[]);}catch{return[];}}
function val(row,key){const v=row?.[key];if(v===null||v===undefined||v==='')return'—';if(typeof v==='number')return Number.isFinite(v)?v.toLocaleString('vi-VN',{maximumFractionDigits:4}):'—';return String(v);}
function splitRow(line){const t=String(line||'').trim();if(!t.startsWith('|'))return[];const b=t.slice(1).endsWith('|')?t.slice(1,-1):t.slice(1);return b.split('|').map(x=>x.trim());}
function inspect(text){const lines=String(text||'').split(/\r?\n/), tabs=(text.match(/\t/g)||[]).length,pipes=(text.match(/\|/g)||[]).length;let format='plain/unknown',delimiter='—';if(lines.some(x=>x.trim().startsWith('|')&&x.includes('|'))){format='markdown-table';delimiter='|';}else if(tabs){format='tab-separated';delimiter='TAB';}else if(lines.some(x=>x.includes(','))){format='comma-separated/plain';delimiter=',';}return{lines,format,delimiter,tabs,pipes};}
function firstRow(text){const info=inspect(text),trs=info.lines.filter(x=>/^\s*\|/.test(x)&&x.includes('|')).map(splitRow);for(let i=0;i<trs.length-1;i++){const r=trs[i],sep=r.length&&r.every(c=>/^\s*:?-{1,}:?\s*$/.test(c)||c==='');if(!sep)continue;for(let j=i+1;j<trs.length;j++){const c=trs[j];if(c.every(x=>/^\s*:?-{1,}:?\s*$/.test(x)||x===''))continue;if(c[0])return c;}}return[];}
async function captureDebug(){debugState={...debugState,status:'Đang đọc clipboard…'};renderPreview();try{if(!navigator.clipboard?.readText)throw Error('Trình duyệt không hỗ trợ đọc Clipboard.');const text=await navigator.clipboard.readText();if(!text.trim())throw Error('Clipboard đang trống.');const i=inspect(text),raw=firstRow(text),result=parseTradingViewPaste(text);debugState={status:`Đã đọc clipboard · ${i.lines.length} dòng · ${raw.length||'không'} cells ở dòng mẫu`,rawRow:raw,parsedRow:result.rows?.[0]||null,result,error:null,rawText:text,lines:i.lines,delimiter:i.delimiter,format:i.format,tabCount:i.tabs,pipeCount:i.pipes};}catch(e){debugState={...debugState,status:'Debug lỗi',error:e?.message||String(e)};}renderPreview();}
function rawInspector(){const lines=debugState.lines||[],rows=lines.slice(0,12).map((line,i)=>`<tr><td>${i}</td><td>${esc(line)}</td><td>${(line.match(/\t/g)||[]).length}</td><td>${(line.match(/\|/g)||[]).length}</td></tr>`).join('');return`<div class="mapping-raw-inspector"><div class="mapping-raw-head"><p class="eyebrow">RAW CLIPBOARD INSPECTOR</p><h3>Clipboard format → parser input</h3><p class="muted">${lines.length} dòng · ${debugState.tabCount} TAB · ${debugState.pipeCount} | · Format: <strong>${esc(debugState.format)}</strong> · Delimiter: <strong>${esc(debugState.delimiter)}</strong></p></div><div class="mapping-raw-table-wrap"><table class="mapping-raw-table"><thead><tr><th>Line</th><th>Raw text</th><th>TAB</th><th>|</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Chưa có dữ liệu. Bấm “Đọc lại Clipboard”.</td></tr>'}</tbody></table></div></div>`;}
function debugPanel(){const r=debugState.result,p=debugState.parsedRow,c=debugState.rawRow||[],mode=r?.mode||'—',count=r?.rows?.length??'—',expected=48,cls=c.length===expected?'debug-ok':'debug-warn';const rows=DEBUG_COLUMNS.map((f,i)=>{const raw=c[i]??'∅';let pv='—';if(p){if(f==='symbol')pv=`ticker=${p.ticker??'—'} · company=${p.company_name??'—'}`;else if(f==='ui_marker')pv='ignored';else pv=val(p,f);}const map=f==='symbol'?'ticker + company_name':f==='ui_marker'?'ignored':f;return`<tr><td>${i}</td><td>${esc(f)}</td><td>${esc(raw)}</td><td>${esc(map)}</td><td>${esc(pv)}</td></tr>`;}).join('');return`<section class="mapping-debug-panel"><div class="mapping-debug-head"><div><p class="eyebrow">PARSER DEBUG</p><h2>Raw Clipboard → Parser → Internal</h2><p class="muted">Debug mẫu dòng đầu tiên để xác định parser đang nhận format, số cell và mapping vị trí.</p></div><button class="btn" id="mappingDebugRefresh">Đọc lại Clipboard</button></div><div class="mapping-debug-summary"><div><span>Mode</span><strong>${esc(mode)}</strong></div><div><span>Parsed rows</span><strong>${esc(String(count))}</strong></div><div><span>Raw cells</span><strong class="${cls}">${c.length} / ${expected}</strong></div><div><span>Status</span><strong>${esc(debugState.status)}</strong></div></div>${debugState.error?`<div class="mapping-debug-error">${esc(debugState.error)}</div>`:''}<div class="mapping-debug-table-wrap"><table class="mapping-debug-table"><thead><tr><th>#</th><th>Parser position</th><th>Raw cell</th><th>Expected mapping</th><th>Parsed value</th></tr></thead><tbody>${rows}</tbody></table></div>${rawInspector()}</section>`;}
function renderPreview(){const main=document.querySelector('.main');if(!main)return;const rows=readRows();main.innerHTML=`<section class="mapping-preview-page"><div class="mapping-preview-head"><div><p class="eyebrow">DATA MAPPING</p><h1>TradingView → Stock Mind</h1><p class="muted">Bảng này tái tạo dữ liệu sau khi parser map sang schema nội bộ. Dùng để kiểm tra trực quan trước khi sửa scoring.</p></div><div class="mapping-preview-meta"><strong>${rows.length.toLocaleString('vi-VN')}</strong><span>mã đã map</span></div></div><div class="mapping-preview-note"><span class="mapping-dot"></span><span>Header hiển thị <strong>tên TradingView</strong> và <strong>Internal field</strong>. Dấu <strong>—</strong> nghĩa là parser hiện chưa nhận giá trị cho field đó.</span></div>${rows.length?`<div class="mapping-table-wrap"><table class="mapping-table"><thead><tr><th class="sticky-col">#</th>${COLUMNS.map(([key,tv])=>`<th title="TradingView: ${esc(tv)}"><span>${esc(tv)}</span><small>${esc(key)}</small></th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr><td class="sticky-col row-number">${i+1}</td>${COLUMNS.map(([key])=>`<td class="${key==='ticker'?'ticker-cell':''}">${esc(val(row,key))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="mapping-empty"><strong>Chưa có dữ liệu.</strong><span>Vào Screen → Import &amp; Screen trước, sau đó mở lại tab Mapping.</span></div>`}${debugPanel()}</section>`;const b=document.getElementById('mappingDebugRefresh');if(b)b.addEventListener('click',captureDebug);}
function activate(){previewOpen=true;document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.remove('active'));const b=document.querySelector(`[data-tab="${TAB_ID}"]`);if(b)b.classList.add('active');renderPreview();}
function ensureTab(){const nav=document.querySelector('.tabs');if(!nav)return;if(nav.querySelector(`[data-tab="${TAB_ID}"]`))return;const b=document.createElement('button');b.className='tab';b.type='button';b.dataset.tab=TAB_ID;b.textContent=TAB_LABEL;b.title='Preview dữ liệu după mapping';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();activate();});nav.appendChild(b);}
function observe(){if(observerStarted)return;observerStarted=true;const root=document.body;const observer=new MutationObserver(()=>{ensureTab();});observer.observe(root,{childList:true,subtree:true});ensureTab();}
function boot(){observe();document.addEventListener('click',e=>{if(e.target.closest('.tabs .tab:not([data-tab="mapping-preview"])'))previewOpen=false;},true);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();